# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.robot.com/cruise/go-retry
    steps:
    - checkout
    # specify any bash command here prefixed with `run: `
    - run:
        name: Download dependency
        command: |
          go get -v -t -d ./...
    - run:
        name: Run tests
        command: |
          go test -v ./...
    - run:
        name: Generate code coverage
        command: |
          ./go.test.sh